language: python
python:
  - "3.3"
  - "3.4"
# command to install dependencies
before_install:
    - sudo add-apt-repository -y ppa:kalakris/cmake
    - sudo apt-get update -qq
install:
  - pip install .
  - pip install -r requirements.txt
  # CMake, require newer version, than in Travis
  - sudo apt-get install libXxf86vm-dev cmake
  # SDL2
  - curl -O http://www.libsdl.org/release/SDL2-2.0.0.tar.gz
  - tar -xzvf SDL2-2.0.0.tar.gz
  - (cd SDL2-2.0.0 && ./configure && make && sudo make install)
# command to run tests
script:
    - (cd gfx_cube && cargo build -v)
    - (cd image && cargo build -v)
    - (cd paint && cargo build -v)
    - (cd deform && cargo build -v)
    - (cd user_input && cargo build -v)
    - (cd sprite && cargo build -v)
    - (cd freetype && cargo build -v)
    - py.test
