language: python
python:
  - "3.3"
  - "3.4"
# command to install dependencies
before_install:
  - sudo add-apt-repository -y ppa:kalakris/cmake
  - sudo apt-get update -qq
install:
  - pip install -e .
  - pip install -r requirements.txt
  - pip install pep8 --use-mirrors
  # CMake, require newer version, than in Travis
  - sudo apt-get install libXxf86vm-dev cmake
  # SDL2
  - curl -O http://www.libsdl.org/release/SDL2-2.0.3.tar.gz
  - tar -xzvf SDL2-2.0.3.tar.gz
  - (cd SDL2-2.0.3 && ./configure && make -j2 && sudo make install)
  - ldconfig -n /usr/local/lib
before_script:
  - pep8
# command to run tests
script:
  - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH; py.test
